// Generated by Selenium IDE

import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

import java.util.*;

public class LoginTest extends BaseTest {


    @Test
    public void loginnegative() {
        homePage.goToLoginPage();
        driver.findElement(By.cssSelector(".fa")).click();
        {
            List<WebElement> elements = driver.findElements(By.id("flash"));
            assert (elements.size() > 0);
        }
    }

    @Test
    public void loginpositive() {
        homePage.goToLoginPage();
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("tomsmith");
        driver.findElement(By.id("password")).sendKeys("SuperSecretPassword!");
        driver.findElement(By.cssSelector(".fa")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".icon-2x"));
            assert (elements.size() > 0);
        }
    }
}
